### PR TITLE
Extended encoding

### PR DESCRIPTION
**Pull request by koa**
Supporting all characters allows accessing and correcting devices previously manipulated directly

### CODE REVIEW

**Comment by ferrohd** [comment]
Mikrotik is not consistent at all about character set compatibility between console, winbox and API ([ref1](https://forum.mikrotik.com/viewtopic.php?t=106053), [ref2](https://forum.mikrotik.com/viewtopic.php?t=147369), https://github.com/home-assistant/core/issues/44111)

I wouldn't even bother adding that. I'd prefer to have `CommandBuilder::add_raw_command(&[u8])` (or something similar) and handle it at application level and not on library level.

**Comment by koa** [comment]
> Mikrotik is not consistent at all about character set compatibility between console, winbox and API ([ref1](https://forum.mikrotik.com/viewtopic.php?t=106053), [ref2](https://forum.mikrotik.com/viewtopic.php?t=147369), [home-assistant/core#44111](https://github.com/home-assistant/core/issues/44111))
> 
> I wouldn't even bother adding that. I'd prefer to have `CommandBuilder::add_raw_command(&[u8])` (or something similar) and handle it at application level and not on library level.

I did some tests with a WebFig on a hEX laying around on my desktop.
There are 3 goals for me (I need them for the next layer of my application):
1. Read the configuration out of the device whatever was done to this device before (as long as it is still accessible)
2. Allow to write any useful configuration to the device
3. Be sure anything successfully written configuration comes back as it was written before

My experiments (and some reading between the lines of the documentation, https://help.mikrotik.com/docs/spaces/ROS/pages/47579229/Scripting#Scripting-ConstantEscapeSequences) showed there is a latin1 character set used on the device. So all the reading operations needs to treat the strings as latin1.
For the writing I can see 2 useful approaches: 
1. Return an error whenever there is a character beyond 7-Bit ASCII
2. Treat them as Latin1 and return an error whenever there is a character beyond 255 (8 Bit)

As I can see no disadvantage on the 8-Bit-Approach as long as you feed only 7-Bit characters I would prefer the later.

Sorting all this arguments I can see a big error in my proposal: Characters beyond 255 are silently ignored. They should result in an error in order to make the API reliable.

What do you think?

**Comment by koa** [comment]
Hmm.
One remark for the beginning: It seems Mikrotik on Webfig uses latin1 and not Windows 1252 (At least on my machine, could be client dependent).

I can agree with only supporting ASCII for writing because everything else is not supported correctly.

There are problems for me, when the API crashes every time when a user has entered a non ascii-character on the device directly (bypassing the rust client for the API), I have seen such "solutions" in my career and the fight with the users to do no such stupid thing like copy-paste something from a email or another dubious source. Assuming every string is utf-8 compatible is a problem here.
I can see 2 approaches to fix this problem
1. return everything as [u8], so the user need to decide how to make a string out of it (and he can also deal with the problem or ignore it). Possible add some optional convenience methods on top to allow string access for users who doesn't care, when the API fails, whenever a user has entered something stupid onto the device directly.
2. use an ASCII compatible 8 bit encoding for strings (doesn't really matter which). Anything above code point 127 is undefined, but defined and reproducible

On the other hand it is clear routeros cannot handle the full Unicode spectrum. So in my opinion it is not correct, when the API seems to be able sending UTF-8 sequences to the device (In fact it is able, but the output on the device will not meet the expectations of the most developers).
So here I can see 2 similar solutions to the dilemma:
1. Process u8, not strings. So the API-User needs to deal with the whole char set problem (possible some additional convenience methods with panic whenever there is a non ASCII character)
2. use an ASCII compatible 8 bit encoding for strings with a runtime error whenever there is an invalid code point.

When I read your arguments I assume you want to avoid to make too much decisions for the user, so I assume you would prefer to use [u8] instead of str.

**Comment by ferrohd** [comment]
> return everything as [u8], so the user need to decide how to make a string out of it (and he can also deal with the problem or ignore it). Possible add some optional convenience methods on top to allow string access for users who doesn't care, when the API fails, whenever a user has entered something stupid onto the device directly.

I've opted for this solution regarding reading the response from the router. I guess the potential string issue could be in the values of attributes and nowhere else? I've opened a PR with my solution #26 . Basically add another field with the "raw" attribute values. Feel free to comment if you see a better one.

> When I read your arguments I assume you want to avoid to make too much decisions for the user, so I assume you would prefer to use [u8] instead of str.

Yes! What do people call this? "Unopinionated"? Yeah
So writing to the router raw bytes would use something like `CommandBuilder<Cmd>::raw_attribute(key: &str, value: Option<&[u8]>)`


Ah this is all based on the assumption that the problematic strings are only in attribute values. This is reasonable to me because afaik attribute keys are defined by RouterOS. Could be wrong tho.

Wdyt?

**Comment by koa** [comment]
In theory I agree: the problem is only the attribute value not the attribute name (and the command).
But switching them all to [u8] instead of str brings 2 additional features:
1. The rust compiler checks constants already for invalid values
2. I found a way appending them into a command without an additional temporary copy

Currently I am working on a commit to switch the whole API to use anywhere [u8] (and try to avoid additional cluttering in the API). Before I push the next proposal I want to adapt also my client.

Btw: Possible you have missed the refactoring of the commit [b39ae85](https://github.com/ferrohd/mikrotik-rs/pull/22/commits/b39ae858a88d846e86dbe52e80c2df5cd49ecef9): It fixes another problem, occurring when a user has managed to put a null byte into a field

**Pull request closed without merging**
